language: go

go:
  - '1.13'

env:
  global:
    - GOFLAGS="-trimpath"

go_import_path: arnested.dk/go/healthy

before_install:
  - GO111MODULE=off go get github.com/mitchellh/gox
  - GO111MODULE=off go get github.com/robertkrimen/godocdown/godocdown
  - GO111MODULE=off go get github.com/frapposelli/wwhrd
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter

before_script:
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make doc ; git diff --quiet # Check the docs are up to date
  - go test -v -race -coverprofile=c.out -covermode=atomic ./...
  - ln c.out coverage.txt # Cover profile should be detected by both CodeClimate and CodeCov
  - go mod vendor && wwhrd check

after_script:
  - rm -rf vendor
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"

deploy:
  # Deploy to Github Releases
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: EMQWlff75Yo2BPWokWpCLwb6E9s86j+L86Sny1T6fSVrCD2U+e3RyKHPfYiSe+rD7LdOW0tFa0AaFoLPqcRpHsgzx3GRBKfVTCTCjaL4PR8DO0Y+7Qf+RxMfBxOYZIEOTxZWIihfO2LzIvfSekm3FOKKse5nwtuRPJpUWp5DPXp9xvD9TVlLu15DMSWLMOoOL1caq4b0LxO+M68BSIW/b0M6dRFnFB90WUOUn4xiKJ7ekW1JHGIV/HgB6yNLeNxEuitEJctuDsO0ZtDdkwXbagr3t1exxuguXcyLGto0v0oY8FYE2gLGepOfxDbFOHaDCsqkvlHhKgZYhL5ify/u0Q+dZqPvACVl3onN7kDNEqwsXGYmoK0HpUxq3GarQYkfCUu4sigoenZT5E1CiJS2kczFCjsxqI6YqF1QxVqCT6DXuKBpDvz69gLF4LKEOSGqMO0ZhXU7oJhF8EDO+YySrbZli42wcmxiJbnT7W66V/N3Qs5177YVDFkic0OlHgjjDAEGYOiU3/oI99NKkUJhFZDIC/Wafjw8JAK1n2HUcPs96BNfjbksH3M21UrFHWJ7mT731yn2CL1clFXIqBUyFkE3ldwJSFBxb3+coYCytssPGBvrkE7x8WX2RwQr5OK8/SjEfg+UjMjO/4LctVJ3SFjWANsisk8ZirGPrNuCDfw=
    file_glob: true
    file: dist/*
    on:
      repo: arnested/healthy
      tags: true
  # Refresh godoc.org documentation
  - provider: script
    script: 'curl --silent -X POST -H "Content-Type: application/x-www-form-urlencoded" https://godoc.org/-/refresh --data "path=arnested.dk%2Fgo%2Fhealthy"'
    on:
      repo: arnested/healthy
      branch: master
  # Refresh goreportcard.com report
  - provider: script
    script: 'curl --silent -X POST -H "Content-Type: application/x-www-form-urlencoded" https://goreportcard.com/checks --data "repo=arnested.dk%2Fgo%2Fhealthy"'
    on:
      repo: arnested/healthy
      branch: master
